IRIS DATASET CLASSIFICATION USING SUPPORT VECTOR MACHINES

In [1]:
#Importing all packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [2]:
#Loading the Iris dataset using the 'read_csv()' function from pandas library
#The read_csv() function read the contents of a dataset stored in .csv or comma separated values format
data = pd.read_csv("Iris.csv")

#Checking if the dataset was read properly
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
#Our prediction target or dependent variable is the 'Species' column
#Separating the dependent variable and the independent variables using dataframe slicing techniques from pandas library
X = data.iloc[:,1:5].values #Set of independent variables
y = data['Species'].values #Dependent variable

In [4]:
#Splitting the dataset into Training Set and Testing Set
#Using the 'train_test_split' function from sklear library
#The first parameter is the set of independent variables, the second parameter is the dependent variable
#The 'test_size' parameter determines the size of the testing dataset. Here we will be using 20% of the dataset for testing
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [5]:
#Model Creation
#Creating an instance for Support Vector Machine model
sv = SVC()

#Fitting the training sets into the model
sv.fit(X_train, y_train)

SVC()

In [6]:
#Predicting the test results
y_predictions = sv.predict(X_test)

In [7]:
#Creating a confusion matrix to measure accuracy
confusion_mat = confusion_matrix(y_test, y_predictions)

#Evaluating the accuracy score
accuracy = accuracy_score(y_test, y_predictions)

#Printing the accuracy score and confusion matrix
print("Accuracy: ",accuracy)
print("Confusion Matrix:\n",confusion_mat)

Accuracy:  0.9333333333333333
Confusion Matrix:
 [[ 6  0  0]
 [ 0 10  0]
 [ 0  2 12]]
